=== alGatto/XML_Groupe4/data/Master.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT master (lecturers?, unites?,  program)>

<!ELEMENT lecturers (lecturer+) >
<!ELEMENT lecturer (name, last_name, mail?, phone?, site*) >

<!ELEMENT unites (unite+) >
<!ELEMENT unite (name, liste_ref_lecturers?, credits, resume?, plan?, place*) >
<!ELEMENT liste_ref_lecturers (ref_lecturer+) >
<!ELEMENT plan (hour_cours, hour_td, hour_tp) >

<!ELEMENT program (parcour+ | specialty) >
<!ELEMENT specialty (responsable+, name, description, parcour+) >
<!ELEMENT parcour (responsable+, name, description, liste_debouch?, semester+) >
<!ELEMENT liste_debouch (debouch*) >
<!ELEMENT semester (bloc+) >
<!ELEMENT bloc (liste_ref-unite) >
<!ELEMENT liste_ref-unite (ref-unite+) >

<!ELEMENT ref_lecturer (#PCDATA) >
<!ELEMENT ref-unite (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT last_name (#PCDATA) >
<!ELEMENT mail (#PCDATA) >
<!ELEMENT phone (#PCDATA) >
<!ELEMENT site (#PCDATA) >
<!ELEMENT credits (#PCDATA) >
<!ELEMENT resume (#PCDATA) >
<!ELEMENT hour_cours (#PCDATA) >
<!ELEMENT hour_td (#PCDATA) >
<!ELEMENT hour_tp (#PCDATA) >
<!ELEMENT place (#PCDATA) >
<!ELEMENT debouch (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT responsable (#PCDATA) >

<!ATTLIST lecturer
          id ID #REQUIRED>
<!ATTLIST unite
          id ID #REQUIRED>
<!ATTLIST ref_lecturer
          ref_lecturer IDREF #REQUIRED>
<!ATTLIST responsable
          ref_lecturer IDREF #REQUIRED>
<!ATTLIST semester
          id ID #REQUIRED>
<!ATTLIST bloc
          role ID #REQUIRED>
<!ATTLIST ref-unite
          ref-unite IDREF #REQUIRED>
<!ATTLIST parcour
          id ID #REQUIRED>

=== alGatto/XML_Groupe4/data/Master.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE master SYSTEM "Master.dtd">
<master>
    <lecturers>
        <lecturer id="AZZAG">
            <name>AZZAG </name>
            <last_name>Samir</last_name>
            <mail>samir.azzag@ynov.com</mail>
            <phone>04.91.01.02.03</phone>
            <site>samir-azzag.fr</site>
        </lecturer>
        <lecturer id="BATISTONI">
            <name>BATISTONI</name>
            <last_name>Eric</last_name>
            <mail>eric.batistoni@ynov.com</mail>
        </lecturer>
        <lecturer id="CHAUVET">
            <name>CHAUVET</name>
            <last_name>Emmanuel</last_name>
            <mail>emmanuel.chauvet@ynov.com</mail>
            <phone>04.91.01.02.04</phone>
        </lecturer>
        <lecturer id="ANGLES">
            <name>ANGLES </name>
            <last_name>Renaud</last_name>
            <mail>renaud.angles@ynov.com</mail>
            <phone>04.91.01.02.05</phone>
            <site>renaud-angles.fr</site>
        </lecturer>
    </lecturers>
    <unites>
        <unite id="ENSMAU4">
            <name>.NET</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="AZZAG"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <plan>
                <hour_cours>15h</hour_cours>
                <hour_td>8h</hour_td>
                <hour_tp>5h</hour_tp>                
            </plan>
            <place>Aix-en-Provence</place>
            <place>Lyon</place>
            <place>Bordeaux</place>
        </unite>        
        <unite id="ENSMBU4">
            <name>CCNP</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="BATISTONI"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <resume>Architecture en couches, standard OSI - Couche physique - Couche liaison de Données - Réseau IP - Algorithmes de routage, routage IP - Protocole TCP/IP - Couche Application : HTTP, SMTP, FTP, ... - protocoles cryptographiques (terminologie, architecture à clef publique). - Sécurité des réseaux.</resume>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>
            </plan>            
            <place>Aix-en-Provence</place>
            <place>Lyon</place>
            <place>Bordeaux</place>
        </unite>
        <unite id="ENSMBU10">
            <name>CISSP</name>
            <credits>3</credits>
        </unite>
        <unite id="ENSMCU3">
            <name>Développement : Unity- applications mobiles et jeux vidéos</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="AZZAG"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>6</credits>
        </unite>
        <unite id="ENSMCU2">
            <name>Développement : programmation fonctionnelle</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="AZZAG"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>6</credits>
        </unite>
        <unite id="ENSMCU1">
            <name>ECM : Gestion de contenu et documents (ECM)</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="CHAUVET"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>6</credits>
        </unite>
        <unite id="ENSMBU8">
            <name>ETL, Big Data, HADOOP</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="BATISTONI"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>
            </plan>
            <place>Lyon</place>
            <place>Bordeaux</place>
        </unite>
        <unite id="ENSMBU9">
            <name>CCNP</name>
            <credits>3</credits>
        </unite>
        <unite id="ENSMAU2">
            <name>J2EE</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="CHAUVET"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <plan>
                <hour_cours>20h</hour_cours>
                <hour_td>20h</hour_td>
                <hour_tp>20h</hour_tp>
            </plan>
            <place>Bordeaux</place>
        </unite>
        <unite id="ENSMCU4">
            <name>Réseau : Docker</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="BATISTONI"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>6</credits>
        </unite>
        <unite id="ENSMBU5">
            <name>Supervision systems</name>
            <credits>6</credits>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>
            </plan>
            <place>Bordeaux</place>
            <place>Aix-en-Provence</place>
        </unite>
        <unite id="ENSMBU2">
            <name>Technologies Microsoft</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="AZZAG"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>                
            </plan>
            <place>Bordeaux</place>
            <place>Aix-en-Provence</place>
            <place>Lyon</place>
        </unite>
        <unite id="ENSMBU3">
            <name>Virtualisation - VMWare</name>
            <credits>6</credits>
            <place>Bordeaux</place>
            <place>Aix-en-Provence</place>
            <place>Lyon</place>
        </unite>
        <unite id="ENSMBU1">
            <name>Virtualisation du poste de travail</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="AZZAG"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>  
            </plan>
            <place>Bordeaux</place>
            <place>Aix-en-Provence</place>
            <place>Lyon</place>            
        </unite>
        <unite id="ENSMAU1">
            <name>Web Services SOA SOAP</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="AZZAG"></ref_lecturer>
                <ref_lecturer ref_lecturer="CHAUVET"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>3</credits>
            <resume>XML - SOA - SOAP - REST - J2EE</resume>
            <plan>
                <hour_cours>20h</hour_cours>
                <hour_td>20h</hour_td>
                <hour_tp>20h</hour_tp>  
            </plan>
            <place>Aix-en-Provence</place>      
        </unite>
        <unite id="ENSMBU7">
            <name>Web Sémantique SEOc</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="ANGLES"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>6</credits>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>  
            </plan>
            <place>Bordeaux</place>      
        </unite>
        <unite id="ENSMAU3">
            <name>xamarin</name>
            <liste_ref_lecturers>
                <ref_lecturer ref_lecturer="BATISTONI"></ref_lecturer>
            </liste_ref_lecturers>
            <credits>6</credits>
            <plan>
                <hour_cours>20h</hour_cours>
                <hour_td>20h</hour_td>
                <hour_tp>20h</hour_tp>  
            </plan>
            <place>Aix-en-Provence</place>      
        </unite>        
        <unite id="ENSMBU6">
            <name>Marketing Digital</name>
            <credits>3</credits>
            <plan>
                <hour_cours>10h</hour_cours>
                <hour_td>10h</hour_td>
                <hour_tp>10h</hour_tp>
            </plan>
            <place>Bordeaux</place>
        </unite>        
    </unites>
    <program>
        <parcour id="Master1_INGESUP">
            <responsable ref_lecturer="AZZAG"></responsable>
            <name>Master 1 INGESUP</name>
            <description>L'objectif de cette première année est de donner les bases indispensables permettant, ...</description>
            <liste_debouch>
                <debouch>Administrateur de bases de données ou d'entrepôts de données</debouch>
                <debouch>Administrateur ou architecte de systèmes d'information</debouch>
                <debouch>Administrateur réseau/système</debouch>
                <debouch>Architecte logiciel</debouch>
                <debouch>Chef de projets</debouch>
                <debouch>Chercheur et enseignant-chercheur</debouch>
                <debouch>Consultant fonctionnel</debouch>
                <debouch>Ingénieur d'études, de recherche et de développement</debouch>
                <debouch>Ingénieur développeur d'applications Web</debouch>
                <debouch>Ingénieur intégration</debouch>
                <debouch>Responsable qualité et/ou sécurité Informatique</debouch>
            </liste_debouch>
            <semester id="semestre1">
                <bloc role="majeur1">
                    <liste_ref-unite>
                        <ref-unite ref-unite="ENSMAU1"></ref-unite>
                        <ref-unite ref-unite="ENSMAU2"></ref-unite>
                        <ref-unite ref-unite="ENSMAU3"></ref-unite>
                        <ref-unite ref-unite="ENSMAU4"></ref-unite>
                        <ref-unite ref-unite="ENSMBU1"></ref-unite>
                        <ref-unite ref-unite="ENSMBU2"></ref-unite>
